server:
  port: 8761
  address: https://service-registry-cahox.cloud.okteto.net/

spring:
  application:
    name: service-registry

management:
  endpoint:
    health:
      enabled: true

eureka:
  instance:
    hostname: https://service-registry-cahox.cloud.okteto.net/
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: https://service-registry-cahox.cloud.okteto.net:8761/eureka/
