server:
  port: 8761

spring:
  application:
    name: service-registry

management:
  endpoint:
    health:
      enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
