server:
  port: 8761
  address: https://service-registry-cahox.cloud.okteto.net/

spring:
  application:
    name: service-registry

management:
  endpoint:
    health:
      enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
