apiVersion: v1
kind: Service
metadata:
  name: service-registry
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: clashbots
spec:
  type: ClusterIP
  ports:
    - name: service-registry
      port: 8761
  selector:
    app: clashbots